stark:
  global:
    author: qiyu
    outputDir: output/
    fileOverride: true
    open: false
  datasource:
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.253:3386/ipark?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: ipark
    password: ipark
  package:
    parent: ai.ii.ipark.cloud.user
  strategy:
    entityLombokModel: true
    restControllerStyle: true
    superServiceImplClass: com.wt.stark.service.BaseServiceImpl
  template:
    entity: template/entity.java
    mapper: template/mapper.java
    xml: template/mapper.xml
    service: template/service.java
    serviceImpl: template/serviceImpl.java
    controller: template/controller.java


